Sold out message
skycoin/teller pull request #195
Opened 2018-01-19 06:46 UTC by briancaine

#193 and #177 

I don't have Chinese or Russian translations done for the strings I added though.

2018-01-19 08:13 UTC, gz-c requested changes
You have to put the same keys into the other translation files

2018-01-19 08:13 UTC, gz-c commented on src/sender/dummy.go
> +	coin_str, err := droplet.ToString(s.coins)
Go uses camelCase

2018-01-20 01:55 UTC, briancaine commented on src/sender/dummy.go
> +	coin_str, err := droplet.ToString(s.coins)
https://github.com/skycoin/teller/pull/195/commits/ef381bb6c23ee701c3433d84a5712119242cc735

Fixed.

2018-01-20 02:08 UTC, briancaine commented
@gz-c Added the keys with English transations.

2018-01-20 03:06 UTC, gz-c approved these changes

2018-01-20 03:06 UTC, merged