move enabled to scanner struct
skycoin/teller pull request #244
Opened 2018-03-22 11:15 UTC by therealssj

2018-03-22 15:30 UTC, gz-c requested changes
Update the default config.toml

2018-03-22 17:45 UTC, therealssj commented
https://github.com/skycoin/teller/pull/235
Has same changes and more. Best to merge that

2018-03-22 17:46 UTC, gz-c commented
takes longer to review multiple changes combined into one, especially a large change like that

2018-03-23 05:08 UTC, gz-c approved these changes

2018-03-23 05:08 UTC, merged